#!/bin/bash
#|

set -euo pipefail
scriptdir=$(cd $(dirname $0) && pwd)
scriptpath=$scriptdir/$(basename $0)
sbcl --script $scriptpath

exit $?
|#

(let ((quicklisp-init (merge-pathnames "quicklisp/setup.lisp" (user-homedir-pathname))))
  (when (probe-file quicklisp-init)
    (load quicklisp-init)))
(ql:quickload "trivia")
(ql:quickload "fiveam")
(require :asdf)

(asdf:load-system :contextual)
(asdf:test-system :contextual)
