name: CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    name: ${{matrix.lisp}} on ${{matrix.os}}
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        lisp: [sbcl-bin]
        os: [ubuntu-latest]
      fail-fast: true
    steps:
    - uses: actions/checkout@v4
    - name: Update APT
      shell: bash
      run: sudo apt-get update

    - name: Install GPG
      shell: bash
      run : sudo apt-get install gpg

    - name: Install SBCL
      if: ${{matrix.lisp == 'sbcl-bin'}}
      shell: bash
      run: sudo apt-get install sbcl

    - name: Install Quicklisp
      shell: bash
      run: |
        gpg --import misc/quicklisp-release-key.gpg
        curl -O https://beta.quicklisp.org/quicklisp.lisp
        curl -O https://beta.quicklisp.org/quicklisp.lisp.asc
        gpg --verify quicklisp.lisp.asc quicklisp.lisp
        sbcl --load quicklisp.lisp --eval '(quicklisp-quickstart:install)'

    - name: Run Tests
      shell: bash
      run: ./run-tests
